# Site wide configuration

title:            Anh Nguyen
locale:           en_US
url:              https://anhnc.me


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
rouge: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Anh Nguyen
  avatar: bio-avatar-anhnc.png
  bio: "Code is read more than it is written, so make it easy to read."
  email: anhnc92@gmail.com
  disqus-shortname:
  twitter: anhnc92
  facebook: # anhnc92
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: anhnc55
  stackoverflow: # 3799893/anhnc   #from a "http://stackoverflow.com/users/123456/username" link
  linkedin: anh-nguyen-203230b1
  xing: #username
  instagram: # anhnc_55
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  appstore: anh-nguyen/id1458306452

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
